-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAfStVSrAhnVKqLG/
VUvo6vdvXINjr+rkSqF9arwrJLWgCgYIKoZIzj0DAQehRANCAAREM/ERqHFDvOvf
4JDQXabcwxMYaTSqpRHIVlvElJlxB8KCdHcfx1ztCg+cC9r95c/c79eQueQsyNri
xfWycHb+
-----END PRIVATE KEY-----