// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2NBAFojxgpwYycnODSwRjLAphPbq7fA',
    appId: '1:931729092950:web:d1903f3bf97262a68826f7',
    messagingSenderId: '931729092950',
    projectId: 'autofirme-196f0',
    authDomain: 'autofirme-196f0.firebaseapp.com',
    storageBucket: 'autofirme-196f0.firebasestorage.app',
    measurementId: 'G-0W8HS4LQCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUu8082tnkxJdxLJTG-oj12hhUTjKLKo',
    appId: '1:931729092950:android:83894e0f8b8b59318826f7',
    messagingSenderId: '931729092950',
    projectId: 'autofirme-196f0',
    storageBucket: 'autofirme-196f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIEgp0QM_dKcqoatmpxpHMH_Ng6DT98rI',
    appId: '1:931729092950:ios:f5fb7b44cd7463d18826f7',
    messagingSenderId: '931729092950',
    projectId: 'autofirme-196f0',
    storageBucket: 'autofirme-196f0.firebasestorage.app',
    iosBundleId: 'com.autofirme.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2NBAFojxgpwYycnODSwRjLAphPbq7fA',
    appId: '1:931729092950:web:a38326b6d2b766038826f7',
    messagingSenderId: '931729092950',
    projectId: 'autofirme-196f0',
    authDomain: 'autofirme-196f0.firebaseapp.com',
    storageBucket: 'autofirme-196f0.firebasestorage.app',
    measurementId: 'G-EGWWRBE8T0',
  );
}
